### ISSUE TITLE
issue from email comments

### ISSUE THREAD

**Issue by VasilyKonnov** [VasilyKonnov/mercury-tz-react#3]
- Нет необходимости использовать слово Component в названии компонентов. В философии реакта все есть компонент.
- Старайся не коммитить дебажный код типа console.log
- Используй props spread для проброса атрибутов в стандартные компоненты. Например, твой компонент Button умеет обрабатывать только 3 атрибута — onClick, type и className. А вот список атрибутов, которые есть у стандартного button — http://htmlbook.ru/html/button. А кроме этого у всех HTML элементов есть набор общих атрибутов — http://htmlbook.ru/html/attr/common. Конечно, далеко не все из них понадобятся в разработке. Но мы можем без лишних затрат предусмотреть универсальность кастомных компонентов используя запись {...props}.
- Избегай лишних оберток DOM-узлов, особенно когда в этом нет особой необходимости (речь про компонент Input)
- CSS классы различных состояний не должны явно задаваться извне. Т.е. логика назначения класса text-input--invalid должна быть зашита внутри компонента Input: например зависеть от props.invalid.
- Называть CSS-классы нужно в соответствии с названием компонентов. Например <Input /> — .input, <Button /> — .button и т.д.

**Comment by VasilyKonnov** [comment]
Внёс все изменения по списку. В одном пункте столкнулся с трудностями. 
Компонент Button выглядит вот так

`function Button(props) {`
 ` const propsClasses = props.className ? props.className.join(" ") : "";`
`  const classNames = [classes["button"], propsClasses].join(" ");`
`  return (`
`    <button className={classNames} type={props.type} onClick={props.onClick}>`
`      {props.children}`
`    </button>`
`  );`
`}`

и если я буду добавлять все свойства через spread оператор  {...props} у меня возникает проблема с соединением классов который пришел из props и тем который задан по умолчанию.

**Comment by akuznetsov-md** [comment]
Ты можешь className задавать после spread:
```
{...props}
className={className}
```

В этом случае переопределения не будет. Чтобы лучше понять, почему так происходит, можно посмотреть во что превращается JSX с props spreading

https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABAIRFKCAUAHATnbAZwEpEBvAKAEhcBTKEXJAHgCM0MkyA6XvAwgF9EEADYBDQoQBy4gLa0AvGQBE7dAhXCA9AD4KgoA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2017%2Creact&prettier=false&targets=&version=7.6.4&externalPlugins=

**Comment by VasilyKonnov** [comment]
Спасибо! Теперь я понял как правильно этим пользоваться
